# Generated by Django 5.0 on 2023-12-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_tag_posts_article_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='id_article',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='id_tag',
            new_name='tag',
        ),
    ]
